version: '3.7'

services:
  mapuche:
    image: ${REGISTRY_HOSTNAME:-}mapuche:${APP_ENVIRONMENT:-dev}
    build:
      context: ./mapuche_391
      dockerfile: Dockerfile
      args:
        - APP_DIRECTORY=${APP_DIRECTORY:-/srv/mapuche}
        - APP_ENVIRONMENT=${APP_ENVIRONMENT:-dev}
    ports:
      - 8000:80
    volumes:
      # Para poder cambiar la config sin rebuildear
      - type: bind
        source: ./mapuche_391/instalador.env
        target: ${APP_DIRECTORY:-/srv/mapuche}/instalador.env
      # Persistencia de personalizaciones
      - type: volume
        source: mapuche-personalizaciones
        target: ${APP_DIRECTORY:-/srv/mapuche}/personalizacion
      # Los datos de toba
      - type: volume
        source: toba-data
        target: /toba-data
      # La configuración de Apache
      - type: volume
        source: apache-conf
        target: /etc/apache2/sites-enabled
    depends_on:
      - db
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
  toba-data:
  apache-conf:
  mapuche-personalizaciones:

