version: '3.7'

services:
  mapuche:
    image: ${REGISTRY_HOSTNAME:-}mapuche:${APP_ENVIRONMENT:-dev}
    build:
      context: ./mapuche_391
      dockerfile: Dockerfile
      args:
        - APP_DIRECTORY=${APP_DIRECTORY:-/srv/mapuche}
        - APP_ENVIRONMENT=${APP_ENVIRONMENT:-dev}
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./mapuche_391/instalador.env
        target: ${APP_DIRECTORY:-/srv/mapuche}/instalador.env
      - type: volume
        source: toba-data
        target: /toba-data
      - type: volume
        source: apache-conf
        target: /etc/apache2/sites-enabled
    depends_on:
      - db
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
  toba-data:
  apache-conf:

